# Generated by Django 5.0.2 on 2024-03-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
