from django.urls import *
from .views import *

urlpatterns = [
    path('signup/',signup,name="signup"),
    path('signin/',signin,name="signin"),
    path('', main, name="main"),
    path('home/',home,name="home"),
    path('aboutus/',aboutus,name="aboutus"),
    path('contactus/',contactus,name="contactus"),
    path('adoption/',adoption,name="adoption"),
    path('accessories/',accessories,name="accessories"),
    path('dogtip/',dogtip,name="dogtip"),
    path('dogs/',dogs,name="dogs"),
    path('cats/',cats,name="cats"),
    path('birds/',birds,name="birds"),
    path('bulldog/',bulldog,name="bulldog"),
    path('beagle/',beagle,name="beagle"),
    path('doberman/',doberman,name="doberman"),
    path('germanshephard/',germanshephard,name="germanshephard"),
    path('goldenretriever/',goldenretriever,name="goldenretriever"),
    path('husky/',husky,name="husky"),
    path('labrador/',labrador,name="labrador"),
    path('pomeranian/',pomeranian,name="pomeranian"),
    path('shiztzu/',shiztzu,name="shiztzu"),
    path('ragdoll/',ragdoll,name='ragdoll'),
    path('siberian_cat/',siberian_cat,name='siberian_cat'),
    path('persian_cat/',persian_cat,name='persian_cat'),
    path('bengal_cat/',bengal_cat,name='bengal_cat'),
    path('peterbald/',peterbald,name='peterbald'),
    path('himalayan/',himalayan,name='himalayan'),
    path('parakeets/',parakeets,name="parakeets"),
    path('cockatiel/',cockatiel,name="cockatiel"),
    path('dove/',dove,name="dove"),
    path('canary/',canary,name="canary"),
    path('hyacinth/',hyacinth,name="hyacinth"),
    path('lovebirds/',lovebirds,name="lovebirds"),
    path('acc_cat/',acc_cat,name="acc_cat"),
    path('acc_dog/',acc_dog,name="acc_dog"),
    path('acc_bird/',acc_bird,name="acc_bird"),
    path('payment/', payment, name='payment'),
    path('success/',success,name="success"),
    path('cart/',cart,name="cart"),
    path('receipt/', receipt, name='receipt'),
    path('sell/',sell,name="sell"),



]